# @package _global_
obs_type: pixels
action_repeat: 2 
encoder: {mlp_keys: '$^', cnn_keys: 'observation', norm: none, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: [400, 400, 400, 400]} 
decoder: {mlp_keys: '$^', cnn_keys: 'observation', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]} 
replay.capacity: 1e6